version: '2'

services:

 prometheus:
  container_name: prometheus
  image: prom/prometheus
  ports:
   - 9090:9090
  volumes:
   - ./prometheus/:/etc/prometheus/
  networks:
   prom-net:
    ipv4_address: 172.18.0.2

 grafana:
  container_name: grafana
  image: grafana/grafana
  ports:
   - 3000:3000
  volumes:
   - grafana-storage:/var/lib/grafana
   - ./grafana/provisioning:/etc/grafana/provisioning
  networks:
   prom-net:
    ipv4_address: 172.18.0.3

 alertmanager:
  container_name: alertmanager
  image: prom/alertmanager
  ports:
   - 9093:9093
  volumes:
   - ./alertmanager/:/etc/alertmanager/
  networks:
   prom-net:
    ipv4_address: 172.18.0.5

 cadvisor:
  container_name: cadvisor
  image: google/cadvisor
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  ports:
   - 8080:8080
  networks:
   prom-net:
    ipv4_address: 172.18.0.6

volumes:
 grafana-storage:

networks:
 prom-net:
  driver: bridge
  ipam:
   config:
    - subnet: 172.18.0.0/16
      gateway: 172.18.0.1
