# prometheus.yml

global:

 scrape_interval: 30s 

 evaluation_interval: 30s

 external_labels:
  monitor: 'my-monitor'

scrape_configs:
 
 - job_name: 'job'
   honor_labels: true
   static_configs:
    - targets: ['<host>:port']
    
 - job_name: 'node-exporter'
   static_configs:
    - targets: ['<host>:9100']
 
 - job_name: 'cadvisor'
   honor_labels: true
   static_configs:
    - targets: ['172.18.0.6:8080']

rule_files:
- 'alert.rules'
alerting:
 alertmanagers:
 - scheme: http
   static_configs:
   - targets: ['172.18.0.5:9093']
